version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  premerge:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: ./premerge.sh
workflows:
    premerge:
      jobs:
        - premerge